export const COMMON_MODULE = "COMMON_MODULE";

export const TOOGLE_SIDE_BAR = "TOOGLE_SIDE_BAR";
export const UPDATE_SIDEBAR_VISIBLE = "UPDATE_SIDEBAR_VISIBLE";
export const TOOGLE_UNFORDABLE = "TOOGLE_UNFORDABLE";

export const GET_SIDEBAR_VISIBLE = "GET_SIDEBAR_VISIBLE";
export const GET_SIDEBAR_UNFORDABLE = "GET_SIDEBAR_UNFORDABLE";
